# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veilarbdirigent
team: oppfolging
replicas:
  min: 2
  max: 2
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: veilarbdirigent/internal/isAlive
    initialDelay: 60
  readiness:
    path: veilarbdirigent/internal/isReady
    initialDelay: 60
prometheus:
  enabled: true
  path: veilarbdirigent/internal/metrics
resources:
  limits:
    cpu: 3
fasitResources:
  used:
  - alias: appdynamics
    resourceType: applicationproperties

  # custom veilarbdirigent props
  - alias: srvveilarbdirigent
    resourceType: credential
  - alias: veilarbdirigentDB
    resourceType: datasource
  - alias: loadbalancer:veilarbdirigent
    resourceType: loadbalancerconfig

  # these apps must run in the same env
  - alias: veilArbOppfolgingAPI
    resourceType: restservice
  - alias: veilArbAktivitetAPI
    resourceType: restservice
  - alias: veilarbmalverkAPI
    resourceType: restservice

  # security resources
  - alias: isso-rp-user
    resourceType: credential
  - alias: isso-host
    resourceType: baseUrl
  - alias: isso-jwks
    resourceType: baseUrl
  - alias: isso-issuer
    resourceType: baseUrl
  - alias: isso.isalive
    resourceType: baseUrl
  - alias: veilarblogin.redirect-url
    resourceType: restservice

alertProfiles:
  - common-java-modules
