# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veilarbdirigent
replicas:
  min: 1
  max: 2
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: veilarbdirigent/internal/isAlive
    initialDelay: 20
  readiness:
    path: veilarbdirigent/internal/selftest
    initialDelay: 20
prometheus:
  enabled: true
  path: veilarbdirigent/internal/metrics
fasitResources:
  used:
  - alias: srvveilarbdirigent
    resourceType: credential
  - alias: veilarbdirigentDB
    resourceType: datasource
  - alias: veilArbOppfolgingAPI
    resourceType: restservice

  # security resources
  - alias: isso-rp-user
    resourceType: credential
  - alias: isso-host
    resourceType: baseUrl
  - alias: isso-jwks
    resourceType: baseUrl
  - alias: isso-issuer
    resourceType: baseUrl
  - alias: isso.isalive
    resourceType: baseUrl
  - alias: veilarblogin.redirect-url
    resourceType: baseUrl
