kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbdirigent
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/veilarbdirigent/veilarbdirigent:{{version}}
  ingresses:
    - https://veilarbdirigent.nais.adeo.no
    - https://app.adeo.no/veilarbdirigent
  port: 8080
  webproxy: true
  prometheus:
    enabled: true
    path: veilarbdirigent/internal/prometheus
  liveness:
    path: veilarbdirigent/internal/isAlive
    initialDelay: 60
  readiness:
    path: veilarbdirigent/internal/isReady
    initialDelay: 60
  replicas:
    min: 1
    max: 1 # It should be 1. Race condition problems may arise if this is greater
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  envFrom:
    - configmap: pto-config
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/prod/creds/veilarbdirigent_p-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /serviceuser/data/prod/srvveilarbdirigent
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/prod/fss/veilarbdirigent/default
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /oracle/data/prod/config/veilarbdirigent_p
        mountPath: /var/run/secrets/nais.io/oracle_config
  env:
    - name: APP_ENVIRONMENT_NAME
      value: p
    - name: VEILARBAKTIVITET_URL
#      value: https://veilarbaktivitet.intern.nav.no
      value: http://veilarbaktivitet.pto.svc.nais.local
    - name: VEILARBAKTIVITET_SCOPE
#      value: api://prod-gcp.dab.veilarbaktivitet/.default
      value: api://prod-fss.dab.veilarbaktivitet/.default
  azure:
    application:
      enabled: true