kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbdirigent
  namespace: default
  cluster: prod-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbdirigent/veilarbdirigent:{{version}}
  ingresses:
    - https://veilarbdirigent.nais.adeo.no
    - https://app.adeo.no/veilarbdirigent
  port: 8080
  prometheus:
    enabled: true
    path: veilarbdirigent/internal/metrics
  liveness:
    path: veilarbdirigent/internal/isAlive
    port: 8080
    initialDelay: 60
  readiness:
    path: veilarbdirigent/internal/isReady
    port: 8080
    initialDelay: 60
  replicas:
    min: 1
    max: 1 # It should be 1. Race condition problems may arise if this is greater
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  configMaps:
    files:
      - pto-config
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/prod/creds/veilarbdirigent-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /serviceuser/data/prod/srvveilarbdirigent
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/prod/fss/veilarbdirigent/default
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  env:
    - APPDYNAMICS_AGENT_ACCOUNT_NAME
    - APPDYNAMICS_CONTROLLER_HOST_NAME
    - APPDYNAMICS_CONTROLLER_PORT
    - APPDYNAMICS_CONTROLLER_SSL_ENABLED
