kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbdirigent
  namespace: {{namespace}}
  cluster: dev-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbdirigent/veilarbdirigent:{{version}}
  ingresses:
    - https://veilarbdirigent-{{namespace}}.nais.preprod.local
    - https://app-{{namespace}}.adeo.no/veilarbdirigent
  port: 8080
  prometheus:
    enabled: true
    path: veilarbdirigent/internal/metrics
  liveness:
    path: veilarbdirigent/internal/isAlive
    port: 8080
    initialDelay: 60
  readiness:
    path: veilarbdirigent/internal/isReady
    port: 8080
    initialDelay: 60
  replicas:
    min: 1
    max: 1 # It should be 1. Race condition problems may arise if this is greater
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  configMaps:
    files:
      - pto-config
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/veilarbdirigent_{{namespace}}-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /serviceuser/data/dev/srvveilarbdirigent
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/preprod/fss/veilarbdirigent/{{namespace}}
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - APPDYNAMICS_AGENT_ACCOUNT_NAME
    - APPDYNAMICS_CONTROLLER_HOST_NAME
    - APPDYNAMICS_CONTROLLER_PORT
    - APPDYNAMICS_CONTROLLER_SSL_ENABLED

