kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbdirigent
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/veilarbdirigent/veilarbdirigent:{{version}}
  ingresses:
    - https://veilarbdirigent-q1.nais.preprod.local
    - https://app-q1.adeo.no/veilarbdirigent
  webproxy: true
  port: 8080
  prometheus:
    enabled: true
    path: veilarbdirigent/internal/prometheus
  liveness:
    path: veilarbdirigent/internal/isAlive
    initialDelay: 60
  readiness:
    path: veilarbdirigent/internal/isReady
    initialDelay: 60
  replicas:
    min: 1
    max: 1 # It should be 1. Race condition problems may arise if this is greater
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  envFrom:
    - configmap: pto-config
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/veilarbdirigent_q1-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /serviceuser/data/dev/srvveilarbdirigent
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/preprod/fss/veilarbdirigent/q1
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /oracle/data/dev/config/veilarbdirigent_q1
        mountPath: /var/run/secrets/nais.io/oracle_config
  accessPolicy:
    outbound:
      external:
        - host: veilarboppfolging.intern.dev.nav.no
  env:
    - name: APP_ENVIRONMENT_NAME
      value: q1
    - name: VEILARBAKTIVITET_URL
      value: https://veilarbaktivitet.intern.dev.nav.no
    - name: VEILARBAKTIVITET_SCOPE
      value: api://dev-gcp.dab.veilarbaktivitet/.default
    - name: VEILARBOPPFOLGING_URL
      value: https://veilarboppfolging.intern.dev.nav.no
    - name: VEILARBOPPFOLGING_SCOPE
      value: api://dev-gcp.poao.veilarboppfolging/.default
  azure:
    application:
      enabled: true