CREATE TABLE TASK (
  ID NVARCHAR2(255) NOT NULL,
  TYPE NVARCHAR2(50) NOT NULL,
  STATUS NVARCHAR2(50) NOT NULL,
  CREATED TIMESTAMP(6) DEFAULT SYSDATE,
  ATTEMPTS NUMBER(3, 0) DEFAULT 0,
  NEXT_ATTEMPT TIMESTAMP(6) DEFAULT SYSDATE,
  LAST_ATTEMPT TIMESTAMP(6),
  DATA CLOB NOT NULL,
  RESULT CLOB,
  ERROR NVARCHAR2(1024),
  CONSTRAINT TASK_PK PRIMARY KEY (ID)
);

CREATE INDEX JSK_STATUS_IDX ON TASK(STATUS);